#!/usr/bin/env node
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));
try {
  const { main } = await import(join(__dirname, 'zeinc-bundle.mjs'));
  main();
} catch {
  try {
    const { main } = await import(join(__dirname, 'zeinc-build/zein/zein.mjs'));
    main();
  } catch {
    const { execFileSync } = await import('child_process');
    try {
      execFileSync(join(__dirname, 'zeinc.escript'), process.argv.slice(2), { stdio: 'inherit' });
    } catch { process.exit(1); }
  }
}
